name: Build and Release Edgeble Linux-6.1-stan-rk4.1

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: Edgeble Kernel-6.1 runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/known_hosts

          # Configure SSH to use this key for GitLab
          echo -e "Host gitlab.com\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config

          # Test the SSH connection (optional)
          ssh -T git@gitlab.com || echo "SSH connection test failed, but continuing..."

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y gcc-9 openssl devscripts build-essential crossbuild-essential-arm64 bc bison
          sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libelf-dev libssl-dev kmod cpio libssl-dev

      - name: Clone and Compile
        run: |
          git clone --branch linux-6.1-stan-rkr4.1 git@gitlab.com:edgeble/core/kernel-6.1.git && cd kernel-6.1
          export CROSS_COMPILE=aarch64-linux-gnu-
          ARCH=arm64 make rockchip_linux_defconfig edgeble-6tops.config
          mkdir -p ${{ github.workspace }}/out
          mkdir -p ${{ github.workspace }}/out/linux-6.1-stan-rk4.1
          mkdir -p ${{ github.workspace }}/out/dtb/rockchip
          mkdir -p ${{ github.workspace }}/out/modules-6.1-stan-rk4.1
          ARCH=arm64 make dtbs Image -j 16; ARCH=arm64 make modules -j 16; ARCH=arm64 make modules_install INSTALL_MOD_PATH=${{ github.workspace }}/out

      - name: Copy deb files and create archive
        run: |
          echo "Copy DTB:"
          cp -fv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtb ${{ github.workspace }}/out/dtb/rockchip
          cp -fv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtbo ${{ github.workspace }}/out/dtb/rockchip
          cp -fv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dtb ${{ github.workspace }}/out/dtb/rockchip

          echo "Copy config:"
          cp -fv ${{ github.workspace }}/kernel-6.1/.config ${{ github.workspace }}/out/linux-6.1-stan-rk4.1

          echo "Create linux-6.1:"
          cp -frv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/Image ${{ github.workspace }}/out/dtb ${{ github.workspace }}/out/linux-6.1-stan-rk4.1

          echo "Create modules-6.1:"
          cp -frv ${{ github.workspace }}/out/lib/modules/* ${{ github.workspace }}/out/modules-6.1-stan-rk4.1

          echo "Create tar.xz"
          cd ${{ github.workspace }}/out/
          tar -Jcf linux-6.1-stan-rk4.1.tar.xz linux-6.1-stan-rk4.1 && tar -Jcf modules-6.1-stan-rk4.1.tar.xz modules-6.1-stan-rk4.1

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.1-rk4.1"
          body: |
            - Add rk4.1 kernel
            - Add edgeble DT, DTBO
          files: |
            ${{ github.workspace }}/out/linux-6.1-stan-rk4.1.tar.xz
            ${{ github.workspace }}/out/modules-6.1-stan-rk4.1.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
